name: Check Links
on:
  push:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install -g markdown-link-check

      - name: Check Links
        run: markdown-link-check .
